### PR TITLE
Refs #125 - Add Setting Screen

### PR DESCRIPTION
**Pull request by rajasone**
ict4d-settings

### CODE REVIEW

**Comment by spipau** [comment]
Quick question, why do you have 2 settings fragments?  `SettingsFragment` and `SettingsFragmentWithToolbar` - is it not possible to just use the `SettingsFragment`?

I didn't try it myself, I'm just wondering why? (I guess you had a reason 😉 )

**Comment by rajasone** [comment]
@spipau As our current application architecture each fragment is `responsible` to show/handle it's toolbar, `SettingsFragment` is of type `PreferenceScreen` so it is not `possible` to include a toolbar in `SettingsFragment`, `BaseFragment` is responsible to handle the toolbar and `Up Navigation` so i created a fragment named as `SettingsFragmentWithToolbar` which is just a container for `Toolbar and SettingsFragment`, I think it is a clean solution to re-sue the `BaseFragment` toolbar and navigation handling

**Comment by spipau** [comment]
> Maybe we can improve this condition because currently if i open my app at 11:55 pm and after 5 minutes i open my app again (12:00am) this condition return `true` because we have different day of the month, it is working fine because of the another condition which checks the `size of existing news`, may be we can use `Difference` class to get the difference in hours, i think it will be more efficient, it is not something really critical it's just a thought :) please check this [link ](https://www.mkyong.com/java8/java-8-period-and-duration-examples/)for `Difference` class, thanks :)

You're right, but I don't think that it is a big problem. More like a nice to have thing, I don't think we need to be very precise here. But good point 😉

**Comment by spipau** [comment]
> @spipau As our current application architecture each fragment is `responsible` to show/handle it's toolbar, `SettingsFragment` is of type `PreferenceScreen` so it is not `possible` to include a toolbar in `SettingsFragment`, `BaseFragment` is responsible to handle the toolbar and `Up Navigation` so i created a fragment named as `SettingsFragmentWithToolbar` which is just a container for `Toolbar and SettingsFragment`, I think it is a clean solution to re-sue the `BaseFragment` toolbar and navigation handling

OK, I thought so, thanks, I guess it's OK 😄

**Comment by spipau** [comment]
Should we really offer the `Sync News After` feature? I don't know if this necessary. Best practice is to always keep settings to a minimum.

**Comment by rajasone** [comment]
@spipau i don't know either, you are right, may be we just allow user to `Allow Sync Service` option only

**Comment by spipau** [comment]
@rajasone Thanks for removing the option. I just went through your changes and you implemented some logic to display the date of the last update, two things:

1. It doesn't work, I have after a first install news items in my list, but in the settings it displays `Never`
1. Honestly, I would also remove this setting, because it doesn't bring any benefit to the user, but just makes our application more complex. I understand why you put it in, we, as developers are interested in these information, but every normal user is simply not. They don't care when the last updates was, as long the next one will happen. A good best practice for settings is, to keep it really to the minimum and only, really only put in a setting option if it is really necessary.

**Pull request merged**
