### PR TITLE
DAO Unit Tests

### PR DESCRIPTION
**Pull request by spipau**
Finally sets up DAO tests with Robolectic, still many tests missing.

### CODE REVIEW

**Comment by spipau** [comment]
@rajasone Tests are now working and the CI builds the project. There are still many tests missing, but should we merge it and then add them in the future, or should we first finish all the test here? What's your opinion?

**Comment by spipau** [comment]
> @rajasone Tests are now working and the CI builds the project. There are still many tests missing, but should we merge it and then add them in the future, or should we first finish all the test here? What's your opinion?

Ignore this one, I implemented all the tests and we can merge this one if you agree 😉

**Comment by rajasone** [comment]
@spipau yes sure I am agree with you, we should merge this branch and we'll continue to write test later on, thanks for setting up the core of test cases :smile:

**Comment by spipau** [comment]
I actually created all Dao Tests today, so the all database queries are covered with tests 😉

**Pull request merged**
