### PR TITLE
Refs #121 - Feat workmanager

### PR DESCRIPTION
**Pull request by rajasone**
@spipau i try my best to write a clean code using WorkManager api and i also changed `Server` class a bit, we will discuss about this in our upcoming call, please fell free to change/revert anything from this branch :)

### CODE REVIEW

**Comment by spipau** [comment]
I added many changes, but the overall architecture is good! Work Manager seems to have some nice features. You implemented a solution with an ID, but you can do this also out of the box with a flag. I didn't test it very much and I hope I will get a notification tomorrow. Please review my changes and give me feedback of what you think 😉

**Comment by rajasone** [comment]
@spipau looks good to me, you can merge it :)

**Comment by spipau** [comment]
Can't do, because the update function is still missing. I only took care to the work manager implementation. I can continue when I have time, or you check it out

**Comment by spipau** [comment]
I improved the notifications and updated Gradle + Work Manager Lib. 
There is still a TODO --> the notification of every single news doesn't open yet the detail view of the news item. This is not possible yet, since we changed the detail view in another branch. I also don't know yet how this will work with the new navigation lib? Any ideas?

**Comment by spipau** [comment]
I found a way to create a Pending Intent with the new Navigation Lib, but it's not working - don't know why yet 😄 
I added some test code, so when you open the app, then 3 notifications will be displayed, so you see how it got implemented 😉

**Pull request merged**
