### PR TITLE
refs #165 - adds release signing and introduces new Version Code hand…

### PR DESCRIPTION
**Pull request by spipau**
Introduces automatic release signing and prepares [Gradle Play Publisher](https://github.com/Triple-T/gradle-play-publisher) implementation

### CODE REVIEW

**Comment by spipau** [comment]
@rajasone can you please verify if this branch builds on your side? Thanks!

**Comment by rajasone** [comment]
@spipau looks good, build and run perfectly :+1:

**Comment by spipau** [comment]
I set up the [Play Store Publisher Gradle Plugin](https://github.com/Triple-T/gradle-play-publisher). Please check if it still builds on your side. If you agree with the changes, then please provide a code review, thanks!

**Comment by spipau** [comment]
OK... CI doesn't build, does it locally at your machine?

**Comment by spipau** [comment]
I fixed the CI build, @rajasone please review whenever you find the time, thanks! 😉

**Comment by rajasone** [comment]
@spipau honestly I am not able to understand most of the code which you write, all I know it's build and run successfully :laughing:

**Comment by spipau** [comment]
haha, we can have a call sooner or later and I can explain it if you want. Basically I configure the signing and the publishing of our app bundle for the Play Store 😉

**Pull request merged**
