### PR TITLE
Refs #12 #37 - Feat news item animation & update news item adapter

### PR DESCRIPTION
**Pull request by rajasone**

### CODE REVIEW

**Comment by rajasone** [comment]
while pressing the back button to go back to the news fragment the fab action button is still blinking

**Comment by spipau** [comment]
True that, was it different with your solution? (`onBackPressed()`)

**Comment by rajasone** [comment]
yes it was working with `onBackPressed()`

**Comment by rajasone** [comment]
should i change it to `onBackPressed()`

**Comment by spipau** [comment]
OK, thanks!

**Pull request merged**
